name: colcon-test

on: push

jobs:
  colcon-test:
    runs-on: ubuntu-latest
    container: ros:jazzy-ros-base
    steps:
      - name: Checkout toio_msgs
        uses: actions/checkout@v7
        with:
          path: src/toio_msgs

      - name: Install dependencies
        shell: bash
        run: |
          apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -y

      - name: Build
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --packages-up-to toio_msgs

      - name: Test
        shell: bash
        run: |
          source /opt/ros/jazzy/setup.bash
          source install/setup.bash
          colcon test --packages-select toio_msgs --event-handlers console_cohesion+
          colcon test-result --verbose
